### PR TITLE
Fixes the transition on load in chrome

### PR DESCRIPTION
**Pull request by matstc**
Here's a fix for the transitions on load Joel.

FYI, it worked in Firefox (even before the fix) and I'm not certain why this particular fix is necessary. I would suggest moving on.

### CODE REVIEW

**Comment by jelliston** [comment]
Thanks Matt - very strange…
I’ve merged the pull request, however the changes weren’t made to my open landing.js file… were they only made on that “Assignment…” branch, and therefore I need to re-merge with Master?

**Comment by matstc** [comment]
Yes @jelliston, the changes were only pulled into the branch. You'll have to merge or rebase to have them in master.

**Comment by jelliston** [comment]
Thanks @matstc, although I’m having problems merging it…when I try to merge the branch into master it says it’s already up-to-date… but my file still hasn’t changed. And from my SourceTree, it looks like it hasn’t been merged… (see below). Any thoughts?

**Comment by matstc** [comment]
Hard to say what the problem is—we could have a look together next session. But make sure to `git pull` from the branch on your machine before you checkout master and merge: your local machine needs to get up to date after a PR was merged on Github.

**Comment by jelliston** [comment]
Ok, thanks Matt - I tried that, but couldn’t get it to work…  should I stop tracking things with git for the next checkpoints/assignments until we can sort it out… so git can stay ‘clean’?

**Comment by matstc** [comment]
Hi Joel. Better to keep using git as usual without merging this right away.
We'll merge it together.

**Comment by jelliston** [comment]
Hi Matt, sorry to keep bothering you on this! How should I keep going with things, as the next checkpoint requires building on the landing.js file,  which I can’t get to update locally from the changes you made on github? Should I manually copy the changes from github and update the file that way before proceeding?

Joel

**Comment by matstc** [comment]
Hi Joel No worries. Your code, as is, is basically working (it works in
Firefox for me). You should be able to just assume that it works and keep
going. Does that make sense?

**Pull request merged**
